config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  get 'persons/profile'

  resources :acts
  resources :categories
  root 'home#index'

end

app/models/act.rb
class Act < ActiveRecord::Base
  belongs_to :user
  belongs_to :category

  validates :amount,      numericality: {greater_than: 0, allow_nil: true, presence: true}
  validates :user_id,     numericality: {greater_than: 0, allow_nil: true, presence: true}
  validates :category_id, numericality: {greater_than: 0, allow_nil: true}
  validates :label,       :length => {:minimum => 0, :maximum => 254}
end

app/models/category.rb
class Category < ActiveRecord::Base
  has_many :act
  belongs_to :user

  validates :user_id,     numericality: {greater_than: 0, allow_nil: true, presence: true}
  validates :title,       :presence => true,
            :length => {:minimum => 1, :maximum => 254}
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :act
  has_many :category
end

app/controllers/acts_controller.rb
class ActsController < ApplicationController

  before_filter :find_current_action, only:[:show, :edit, :update, :destroy]
  before_filter :check_admin, only:[:show, :edit, :update, :destroy]
  def index
    @actions = Act
                   .select('acts.*, categories.title as category_title')
                   .joins(:category)
                   .where(user_id:current_user.id)
  end

  # /acts POST
  def create
    @current_action = Act.new
    @current_action.label = params[:act][:label]
    @current_action.amount = params[:act][:amount]
    @current_action.user_id = params[:act][:user_id]
    @current_action.category_id = params[:act][:category_id]
    @current_action.income = params[:act][:income]
    @current_action.save
    if @current_action.errors.empty?
      redirect_to root_path
    else
      render "new"
    end
  end

  # /acts/1/edit GET
  def edit
    @categories = Category.where(user_id:current_user.id,income:@current_action.income)
  end

  # /acts/1 PUT
  def update
    @current_action.update_attributes(act_params)
    if @current_action.errors.empty?
      redirect_to root_path
    else
      render "edit"
    end
  end

  # /acts/1 DELETE
  def destroy
    @current_action.destroy
    redirect_to root_path
  end

  private

  def find_current_action
    @current_action = Act.find(params[:id])
  end

  def check_admin
    render text: "Access Denied", status: 403 unless @current_action.user_id == current_user.id
  end

  def act_params
    params.require(:act).permit(:amount,:label,:category_id,:user_id,:income)
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_filter :set_balance
  before_filter :get_categories
  before_filter :get_actions

  def after_sign_in_path_for(resource)
    root_path
  end

  def after_sign_out_path_for(resource_or_scope)
    request.referrer
  end

  private

  def set_balance
    if user_signed_in?
      @actions = Act.where(user_id: current_user.id)
      $balance = 0
      @actions.each do |b|
        if b.income?
          $balance = $balance +b.amount
        else
          $balance = $balance -b.amount
        end
      end
    else
    end
  end

  def get_categories
    if user_signed_in?
    @income_categories = Category.where(user_id:current_user.id,income:true)
    @expence_categories = Category.where(user_id:current_user.id,income:false)
    end
  end

  def get_actions
    if user_signed_in?

      if params['search_end_period']
        arr_end_period = params['search_end_period'].join.split("-")
        $search_end_period = Date.new(arr_end_period[0].to_i,arr_end_period[1].to_i,arr_end_period[2].to_i).to_time.to_i
      else
        $search_end_period = Time.now.to_time.to_i
      end

      if params['search_start_period']
        arr_start_period = params['search_start_period'].join.split("-")
        $search_start_period = Date.new(arr_start_period[0].to_i, arr_start_period[1].to_i, arr_start_period[2].to_i).to_time.to_i
      else
        $search_start_period = 0
      end


#render text: params['search_start_period']
        @actions = Act
                       .select('acts.*, categories.title as category_title')
                       .joins("left join categories on categories.id = acts.category_id")
                       .where(user_id:current_user.id)
                       .where("acts.created_at >= to_timestamp(:created_at)", {created_at: $search_start_period })
                       .where("acts.created_at <= to_timestamp(:created_at)", {created_at: $search_end_period })
                       .order("created_at DESC")
    end
  end

end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_filter :find_category, only:[:show, :edit, :update, :destroy]
  before_filter :check_admin, only:[:show, :edit, :update, :destroy]
  def index
    @categories = Category.where(user_id:current_user.id)
  end


  # /categories POST
  def create
    @category = Category.new
    @category.title = params[:category][:title]
    @category.user_id = current_user.id
    @category.income = params[:category][:income]
    @category.save
    if @category.errors.empty?
      redirect_to categories_path
    else
      render "new"
    end
  end

  # /categories/1/edit GET
  def edit
    @income = false
  end

  # /categories/1 PUT
  def update
    @category.update_attributes(category_params)
    if @category.errors.empty?
      redirect_to categories_path
    else
      render "edit"
    end
  end

  # /categories/1 DELETE
  def destroy
    @category.destroy
    redirect_to categories_path
  end

  private

  def find_category
    @category = Category.find(params[:id])
  end

  def check_admin
    render text: "Access Denied", status: 403 unless @category.user_id == current_user.id
  end

  def category_params
    params.require(:category).permit(:title,:user_id,:income)
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    if user_signed_in?
      @all_categories = Category.where(user_id:current_user.id)
    end
  end
end

app/controllers/persons_controller.rb
class PersonsController < ApplicationController
  def profile
  end

  def except

  end
end

class OrdersController < ApplicationController
  before_filter :authenticate_user!, except => [:show, :index]

  def index
    # do something
  end

  def show
    # do something
  end

  def create
    # do something
  end

  def except

  end
end

app/helpers/acts_helper.rb
module ActsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/persons_helper.rb
module PersonsHelper
end

app/views/acts/edit.html.erb
<h1>Update Action</h1>

<%= form_for @current_action do |f|%>
    <div class="modal-body">

      <div class="form-group">
        <p><%= f.number_field :amount,class: 'form-control',placeholder: 'Amount' %></p>
        <p><%= f.text_field :label,class: 'form-control',placeholder: 'Label' %></p>
        <%= f.hidden_field :income%>
        <%= f.hidden_field :user_id, value: current_user.id %>
        <p>
          <%= f.collection_select(:category_id,  @categories, :id, :title, {prompt: "Select a category"}, {class: "form-control"}) %>
        </p>
      </div>

    </div>
    <div class="modal-footer">
      <button type="button" class="btn btn-default" data-dismiss="modal">Cancel</button>
      <%= f.submit "Update", class: 'btn btn-primary'%>
    </div>
<% end %>

app/views/acts/index.html.erb
<% if @actions.empty? %>
    <div>No actions</div>
<% else %>
    <table>
      <tr>
        <th>id</th>
        <th>Amount</th>
        <th>Label</th>
        <th>Category</th>
        <th></th>
        <th></th>
      </tr>
      <% @actions.each do |a| %>
          <tr>
            <td><%= link_to a.id, act_path(a) %></td>
            <td><%= a.amount %></td>
            <td><%= a.label %></td>
            <td><%= a.category_title %></td>
            <td><%= link_to " Edit ", edit_act_path(a) %></td>
            <td><%= link_to " Delete ", act_path(a), method: :delete %></td>
          </tr>
      <% end %>
    </table>

<% end %>

app/views/categories/edit.html.erb
<h1>Update Category</h1>

<%= form_for @category do |f|%>
    <div class="modal-body">

      <div class="form-group">
        <p><%= f.text_field :title, class: 'form-control',placeholder: 'Title' %></p>
        <%= f.hidden_field :income %>
        <%= f.hidden_field :user_id, value: current_user.id %>
      </div>
    </div>
    <div class="modal-footer">
      <button type="button" class="btn btn-default" data-dismiss="modal">Cancel</button>
      <%= f.submit "Update", class: 'btn btn-primary'%>
    </div>
<% end %>

app/views/categories/index.html.erb
<h1>Categories</h1>

<% if @categories.empty? %>
    <div>No categories</div>
<% else %>
    <table class="table table-striped">
      <tr>
        <th>Title</th>
        <th>Date</th>
        <th></th>
        <th></th>
      </tr>
      <% @categories.each do |c| %>
          <tr class=<% if c.income? %>"success"<% end %>>
            <td><%= c.title %></td>
            <td width="200"><%= c.created_at %></td>
            <td width="50"><%= link_to " Edit ", edit_category_path(c) %></td>
            <td width="50"><%= link_to " Delete ", category_path(c), method: :delete %></td>
          </tr>
      <% end %>
    </table>

<% end %>

app/views/home/index.html.erb
<% if user_signed_in? %>

    <div class="container">
      <div class="row">
        <%= form_tag root_path, method: :get, class: "form-inline pull-right" do %>


            <div class="form-group">
              <div class="input-group input-large">
                <%= date_field 'search_start_period','', class: "form-control", required:true %>
                <span class="input-group-addon">To</span>
                <%= date_field 'search_end_period','', class: "form-control",required:true %>
              </div>
            </div>


            <div class="form-group">
              <%= submit_tag 'Search', class: "btn btn-md"%>
            </div>
        <% end %>
      </div>
    </div>

    <% if @actions.empty? %>
        <div>No actions</div>
    <% else %>


        <div class="container" style="margin-top: 20px">
          <div class="row">
            <table class="table table-striped">
              <tr>
                <th>Amount</th>
                <th>Label</th>
                <th>Category</th>
                <th>Date</th>
                <th></th>
                <th></th>
              </tr>
              <% @actions.each do |a| %>
                  <tr class=<% if a.income? %>"success"<% end %>>
                    <td><% if a.income? %>+<% else %>-<% end %> <%= a.amount %></td>
                    <td><%= a.label %></td>
                    <td><%= a.category_title %></td>
                    <td width="200"><%= a.created_at %></td>
                    <td width="50"><%= link_to " Edit ", edit_act_path(a) %></td>
                    <td width="50"><%= link_to " Delete ", act_path(a), method: :delete %></td>
                  </tr>
              <% end %>
            </table>
          </div>
        </div>







    <% end %>

    <%else%>

<!-- Landing-->
<div class="container theme-showcase" role="main">

  <!-- Main jumbotron for a primary marketing message or call to action -->
  <div class="jumbotron">
    <h1>Welcome!</h1>
    <p>Manage the incomes and expenses effectively!</p>
    <p><%= link_to 'Try now', new_user_session_path, {:class => 'btn btn-lg btn-primary'} %></p>
  </div>
</div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Income/Expence Tracker</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>


<!-- Fixed navbar -->
<div class="navbar navbar-inverse navbar-fixed-top" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="/">Income/Expence Tracker</a>
    </div>
    <div class="navbar-collapse collapse">
      <% if user_signed_in? %>
        <ul class="nav navbar-nav">
          <li><a href="/categories">Manage Categories</a></li>
        </ul>
      <% end %>
      <div class="pull-right" style="margin-top: 8px;">
        <% if user_signed_in? %>
            <span class="login_email"><%= current_user.email %></span>
            <%= link_to 'Log out', destroy_user_session_path,  {:class => 'btn btn-md btn-danger',:method => :delete}  %>
        <% else %>
            <%= link_to 'Log in', new_user_session_path, {:class => 'btn btn-md btn-danger'} %>
            <%= link_to 'Create an account', new_user_registration_path, {:class => 'btn btn-md btn-danger'}  %>
        <% end %>
      </div>
    </div><!--/.nav-collapse -->

  </div>
</div>

<div class="container">
  <div class="row">

    <% if user_signed_in? %>
      <div class="col-sm-8">

        <!-- Button trigger modal -->
        <button class="btn btn-success btn-md" data-toggle="modal" data-target="#addIncomeModal">
          ADD INCOME
        </button>

        <!-- Modal -->
        <div class="modal fade" id="addIncomeModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
          <div class="modal-dialog">
            <div class="modal-content">
              <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                <h4 class="modal-title text-uppercase" id="myModalLabel">Add Income</h4>
              </div>
              <%= form_for Act.new, {:class => 'x'} do |f|%>
              <div class="modal-body">

                    <div class="form-group">
                      <p><%= f.number_field :amount, class: 'form-control',placeholder: 'Amount' %></p>
                      <p><%= f.text_field :label,class: 'form-control',placeholder: 'Label' %></p>
                      <%= f.hidden_field :income, value: true %>
                      <%= f.hidden_field :user_id, value: current_user.id %>
                      <p>
                        <label>Select a category</label>
                        <%= f.collection_select(:category_id, @income_categories, :id, :title, {allow_blank: "Select a category"}, {class: "form-control"}) %>
                      </p>
                    </div>

              </div>
              <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal">Cancel</button>
                <%= f.submit "Add", class: 'btn btn-primary'%>
              </div>
              <% end %>
            </div>
          </div>
        </div>

        <!-- Button trigger modal -->
        <button class="btn btn-danger btn-md" data-toggle="modal" data-target="#addExpenceModal">
          ADD EXPENCE
        </button>

        <!-- Modal -->
        <div class="modal fade" id="addExpenceModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
          <div class="modal-dialog">
            <div class="modal-content">
              <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                <h4 class="modal-title text-uppercase" id="myModalLabel">Add Expence</h4>
              </div>
              <%= form_for Act.new do |f|%>
                  <div class="modal-body">

                    <div class="form-group">
                      <p><%= f.number_field :amount,class: 'form-control',placeholder: 'Amount' %></p>
                      <p><%= f.text_field :label,class: 'form-control',placeholder: 'Label' %></p>
                      <%= f.hidden_field :income, value: false %>
                      <%= f.hidden_field :user_id, value: current_user.id %>
                      <p>
                        <label>Select a category</label>
                        <%= f.collection_select(:category_id, @expence_categories, :id, :title, {allow_blank: "Select a category"}, {class: "form-control"}) %>
                      </p>
                    </div>

                  </div>
                  <div class="modal-footer">
                    <button type="button" class="btn btn-default" data-dismiss="modal">Cancel</button>
                    <%= f.submit "Add", class: 'btn btn-primary'%>
                  </div>
              <% end %>
            </div>
          </div>
        </div>


        <button class="btn btn-md btn-link text-uppercase" data-toggle="modal" data-target="#addIncomeCategoryModal">
          ADD INCOME CATEGORY
        </button>

        <!-- Modal -->
        <div class="modal fade" id="addIncomeCategoryModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
          <div class="modal-dialog">
            <div class="modal-content">
              <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                <h4 class="modal-title text-uppercase" id="myModalLabel">Add income Category</h4>
              </div>
              <%= form_for Category.new do |f|%>
                  <div class="modal-body">

                    <div class="form-group">
                      <p><%= f.text_field :title, class: 'form-control',placeholder: 'Title' %></p>
                      <%= f.hidden_field :income, value: true %>
                      <%= f.hidden_field :user_id, value: current_user.id %>
                    </div>
                  </div>
                  <div class="modal-footer">
                    <button type="button" class="btn btn-default" data-dismiss="modal">Cancel</button>
                    <%= f.submit "Add", class: 'btn btn-primary'%>
                  </div>
              <% end %>
            </div>
          </div>
        </div>

        <button class="btn btn-md btn-link text-uppercase" data-toggle="modal" data-target="#addExpenceCategoryModal">
          ADD EXPENCE CATEGORY
        </button>

        <!-- Modal -->
        <div class="modal fade" id="addExpenceCategoryModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
          <div class="modal-dialog">
            <div class="modal-content">
              <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                <h4 class="modal-title text-uppercase" id="myModalLabel">Add Expence Category</h4>
              </div>
              <%= form_for Category.new do |f|%>
                  <div class="modal-body">

                    <div class="form-group">
                      <p><%= f.text_field :title, class: 'form-control',placeholder: 'Title' %></p>
                      <%= f.hidden_field :income, value: false %>
                      <%= f.hidden_field :user_id, value: current_user.id %>
                    </div>
                  </div>
                  <div class="modal-footer">
                    <button type="button" class="btn btn-default" data-dismiss="modal">Cancel</button>
                    <%= f.submit "Add", class: 'btn btn-primary'%>
                  </div>
              <% end %>
            </div>
          </div>
        </div>
      </div><!-- /.col-sm-6 -->
        <div class="col-sm-4 ">
          <div class="btn btn-lg pull-right">Balance: <%= $balance %></div>
        </div><!-- /.col-sm-6 -->

    <div class="clearfix"></div>


    <% end %>

      <%= yield %>

  </div>
</div>


</body>
</html>

app/views/persons/profile.html.erb
<h1>Persons#profile</h1>
<p>Find me in app/views/persons/profile.html.erb</p>